configure

    - nMakefile CI

on:
  push:
    branches: [ "release_Q_KernelSU_Exp" ]
  pull_request:
    branches: [ "release_Q_KernelSU_Exp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

- name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
